"""initial schema

Revision ID: f51e751d9c84
Revises: 
Create Date: 2026-07-04 15:59:58.596336

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f51e751d9c84'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anidb_title_index',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aid', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('lang', sa.String(), nullable=True),
    sa.Column('title_type', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('anidb_title_index', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_anidb_title_index_aid'), ['aid'], unique=False)

    op.create_table('folder',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('offline', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('path')
    )
    op.create_table('setting',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('anidb_tag_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('anidb_tag_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('anime',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('folder_id', sa.Integer(), nullable=False),
    sa.Column('directory_path', sa.String(), nullable=False),
    sa.Column('anidb_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('original_title', sa.String(), nullable=True),
    sa.Column('alt_titles', sa.JSON(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('media_type', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('poster_path', sa.String(), nullable=True),
    sa.Column('ident_status', sa.String(), nullable=False),
    sa.Column('match_score', sa.Float(), nullable=True),
    sa.Column('episode_count_expected', sa.Integer(), nullable=True),
    sa.Column('missing_on_disk', sa.Boolean(), nullable=False),
    sa.Column('last_metadata_refresh', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['folder_id'], ['folder.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('anidb_id'),
    sa.UniqueConstraint('directory_path')
    )
    op.create_table('anime_provider_id',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('anime_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['anime_id'], ['anime.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('anime_id', 'provider', name='uq_anime_provider')
    )
    op.create_table('anime_tag',
    sa.Column('anime_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['anime_id'], ['anime.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
    sa.PrimaryKeyConstraint('anime_id', 'tag_id')
    )
    op.create_table('expected_episode',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('anime_id', sa.Integer(), nullable=False),
    sa.Column('ep_number', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('air_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['anime_id'], ['anime.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('anime_id', sa.Integer(), nullable=True),
    sa.Column('job_type', sa.String(), nullable=False),
    sa.Column('result', sa.String(), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['anime_id'], ['anime.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('local_episode',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('anime_id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('ep_number', sa.String(), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('file_mtime', sa.Float(), nullable=False),
    sa.Column('manual_override', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['anime_id'], ['anime.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_path')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('local_episode')
    op.drop_table('job_log')
    op.drop_table('expected_episode')
    op.drop_table('anime_tag')
    op.drop_table('anime_provider_id')
    op.drop_table('anime')
    op.drop_table('tag')
    op.drop_table('setting')
    op.drop_table('folder')
    with op.batch_alter_table('anidb_title_index', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_anidb_title_index_aid'))

    op.drop_table('anidb_title_index')
    # ### end Alembic commands ###
